### ISSUE TITLE
[BUG] 댓글 401 오류 발생

### ISSUE THREAD

**Issue by haesa** [snorose/snorose-front-react#325]
## 🔎 어떤 상황에서 발생한 버그인가요?

- 댓글 목록을 조회하는 곳에서 댓글 조회 응답으로 401 에러가 발생합니다.

**Comment by junheekim61** [comment]
댓글 조회 실패할 경우 FetchLoading animation=false인 거 띄우도록 추가해주시면 감사하겠습니다
